version: '3'
services:
  api:
    build:
      context: .
    container_name: top-api
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./.env:/app/.env
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4.4
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27018:27017
    expose:
      - 27018
    volumes:
      - ./mongo-data:/data/db